// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attention.sql

package sqlitesqlc

import (
	"context"
)

const clearUntilResolvedMutes = `-- name: ClearUntilResolvedMutes :exec
DELETE FROM attention_mutes
WHERE fingerprint = ?1 AND until_at IS NULL
`

func (q *Queries) ClearUntilResolvedMutes(ctx context.Context, fingerprint string) error {
	_, err := q.db.ExecContext(ctx, clearUntilResolvedMutes, fingerprint)
	return err
}

const deleteAttentionMuteByID = `-- name: DeleteAttentionMuteByID :exec
DELETE FROM attention_mutes WHERE id = ?1
`

func (q *Queries) DeleteAttentionMuteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttentionMuteByID, id)
	return err
}

const deleteAttentionRuleOverride = `-- name: DeleteAttentionRuleOverride :exec
DELETE FROM attention_rule_overrides WHERE rule_type = ?1
`

func (q *Queries) DeleteAttentionRuleOverride(ctx context.Context, ruleType string) error {
	_, err := q.db.ExecContext(ctx, deleteAttentionRuleOverride, ruleType)
	return err
}

const getAttentionMuteByID = `-- name: GetAttentionMuteByID :one
SELECT id, user_id, repo_id, rule_type, fingerprint, until_at, reason, created_at, created_by
FROM attention_mutes
WHERE id = ?1
`

func (q *Queries) GetAttentionMuteByID(ctx context.Context, id int64) (AttentionMute, error) {
	row := q.db.QueryRowContext(ctx, getAttentionMuteByID, id)
	var i AttentionMute
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoID,
		&i.RuleType,
		&i.Fingerprint,
		&i.UntilAt,
		&i.Reason,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAttentionRuleOverrides = `-- name: ListAttentionRuleOverrides :many
SELECT rule_type, severity, updated_at
FROM attention_rule_overrides
ORDER BY rule_type
`

func (q *Queries) ListAttentionRuleOverrides(ctx context.Context) ([]AttentionRuleOverride, error) {
	rows, err := q.db.QueryContext(ctx, listAttentionRuleOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttentionRuleOverride{}
	for rows.Next() {
		var i AttentionRuleOverride
		if err := rows.Scan(&i.RuleType, &i.Severity, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAttentionByFingerprint = `-- name: ResolveAttentionByFingerprint :exec
UPDATE attention_items
SET resolved_at = ?1, updated_at = ?2
WHERE fingerprint = ?3 AND resolved_at IS NULL
`

type ResolveAttentionByFingerprintParams struct {
	ResolvedAt  *string
	UpdatedAt   string
	Fingerprint string
}

func (q *Queries) ResolveAttentionByFingerprint(ctx context.Context, arg ResolveAttentionByFingerprintParams) error {
	_, err := q.db.ExecContext(ctx, resolveAttentionByFingerprint, arg.ResolvedAt, arg.UpdatedAt, arg.Fingerprint)
	return err
}
