// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlitesqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, created_at, ip, user_agent)
VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	TokenHash string
	ExpiresAt string
	CreatedAt string
	Ip        string
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, expires_at, created_at, ip, user_agent
FROM sessions
WHERE token_hash = ?1
`

type GetSessionByTokenHashRow struct {
	ID        string
	UserID    int64
	ExpiresAt string
	CreatedAt string
	Ip        string
	UserAgent string
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, instance_id, gitea_user_id, github_user_id, github_instance_id,
       gitlab_user_id, gitlab_instance_id, bitbucket_user_id, bitbucket_instance_id,
       login, email, display_name, avatar_url, is_bootstrap_admin, created_at, updated_at
FROM users
WHERE id = ?1
`

type GetUserByIDRow struct {
	ID                  int64
	InstanceID          *int64
	GiteaUserID         *int64
	GithubUserID        *int64
	GithubInstanceID    *int64
	GitlabUserID        *int64
	GitlabInstanceID    *int64
	BitbucketUserID     *int64
	BitbucketInstanceID *int64
	Login               string
	Email               string
	DisplayName         string
	AvatarUrl           string
	IsBootstrapAdmin    int64
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.GiteaUserID,
		&i.GithubUserID,
		&i.GithubInstanceID,
		&i.GitlabUserID,
		&i.GitlabInstanceID,
		&i.BitbucketUserID,
		&i.BitbucketInstanceID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsBootstrapAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
