// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitesqlc

type AppSetting struct {
	ID                         int64
	InstanceName               string
	SyncHistoryDays            int64
	AttentionLongRunningAfter  string
	RetentionRunsDays          int64
	RetentionWebhooksDays      int64
	RetentionAttentionDays     int64
	UpdatedAt                  string
	GiteaUrl                   string
	GiteaTokenCipher           string
	GiteaWebhookSecretCipher   string
	GiteaAllowPrivateNetwork   *int64
	GiteaAllowUnsignedWebhooks *int64
	OauthClientID              string
	OauthClientSecretCipher    string
	SetupCompleted             int64
	ServerExternalUrl          string
}

type AttentionItem struct {
	ID           int64
	InstanceID   int64
	RepoID       int64
	Type         string
	Severity     string
	EntityType   string
	EntityID     int64
	Title        string
	MetadataJson string
	Fingerprint  string
	OpenedAt     string
	ResolvedAt   *string
	UpdatedAt    string
}

type AttentionMute struct {
	ID          int64
	UserID      *int64
	RepoID      *int64
	RuleType    string
	Fingerprint string
	UntilAt     *string
	Reason      string
	CreatedAt   string
	CreatedBy   *int64
}

type AttentionRuleOverride struct {
	RuleType  string
	Severity  string
	UpdatedAt string
}

type Instance struct {
	ID                          int64
	Name                        string
	BaseUrl                     string
	Version                     string
	CapabilitiesJson            string
	SyncTokenCiphertext         string
	WebhookSecretCiphertext     string
	OauthClientID               string
	OauthClientSecretCiphertext string
	ExternalUrl                 string
	CreatedAt                   string
	UpdatedAt                   string
	ForgeType                   string
	AllowPrivateNetwork         int64
	AllowUnsignedWebhooks       int64
	WebhookVerifiedAt           *string
	WebhookEnsureAt             *string
	WebhookEnsureError          *string
	WebhookVerifyToken          *string
}

type Job struct {
	ID                 int64
	RunID              int64
	RepoID             int64
	ExternalID         int64
	Name               string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	RunnerID           *int64
	RunnerName         string
	HtmlUrl            string
	StartedAt          *string
	CompletedAt        *string
	StepsJson          *string
	NodeID             string
	LabelsJson         *string
	Message            string
}

type NotificationOutbox struct {
	ID                  int64
	Channel             string
	Kind                string
	PayloadJson         string
	Status              string
	Attempts            int64
	NextAttemptAt       *string
	LastError           string
	DedupeKey           string
	CreatedAt           string
	UpdatedAt           string
	SentAt              *string
	ProcessingStartedAt *string
}

type NotificationSetting struct {
	ID                        int64
	Enabled                   int64
	MinSeverity               string
	ImmediateEnabled          int64
	DigestEnabled             int64
	DigestHourUtc             int64
	LastDigestAt              *string
	SmtpEnabled               int64
	SmtpHost                  string
	SmtpPort                  int64
	SmtpTlsMode               string
	SmtpFrom                  string
	SmtpTo                    string
	SmtpUsername              string
	SmtpPasswordCiphertext    string
	SlackEnabled              int64
	SlackWebhookCiphertext    string
	DiscordEnabled            int64
	DiscordWebhookCiphertext  string
	WebhookEnabled            int64
	WebhookUrlCiphertext      string
	UpdatedAt                 string
	IncidentEnabled           int64
	IncidentWebhookCiphertext string
}

type OauthState struct {
	State        string
	CodeVerifier string
	RedirectTo   string
	ExpiresAt    string
	Provider     string
	InstanceID   *int64
	LinkUserID   *int64
}

type Organization struct {
	ID         int64
	InstanceID int64
	ExternalID int64
	Name       string
	FullName   string
	AvatarUrl  string
	SyncedAt   *string
	NodeID     string
}

type PullRequest struct {
	ID               int64
	RepoID           int64
	ExternalID       int64
	Number           int64
	Title            string
	BodyExcerpt      string
	AuthorLogin      string
	AuthorExternalID *int64
	SourceBranch     string
	TargetBranch     string
	HeadSha          string
	BaseSha          string
	State            string
	Draft            int64
	Mergeable        *int64
	MergeableState   string
	ReviewState      string
	CiState          string
	HtmlUrl          string
	CreatedAt        *string
	UpdatedAt        *string
	ClosedAt         *string
	MergedAt         *string
	NodeID           string
}

type Repository struct {
	ID                    int64
	InstanceID            int64
	OrgID                 *int64
	ExternalID            int64
	Owner                 string
	Name                  string
	FullName              string
	DefaultBranch         string
	Private               int64
	Archived              int64
	Empty                 int64
	Fork                  int64
	HtmlUrl               string
	PermissionsMirrorJson string
	LastSyncedAt          *string
	DeletedAt             *string
	RenamedFrom           *string
	CreatedAt             string
	UpdatedAt             string
	NodeID                string
}

type SavedFilter struct {
	ID        int64
	UserID    int64
	Name      string
	QueryJson string
	CreatedAt string
	UpdatedAt string
}

type Session struct {
	ID        string
	UserID    int64
	TokenHash string
	ExpiresAt string
	CreatedAt string
	Ip        string
	UserAgent string
}

type SyncLease struct {
	ID        int64
	Holder    string
	ExpiresAt string
}

type SyncState struct {
	ID            int64
	InstanceID    int64
	Scope         string
	ScopeID       int64
	CursorJson    string
	LastSuccessAt *string
	LastError     *string
	Phase         string
}

type User struct {
	ID                  int64
	InstanceID          *int64
	GiteaUserID         *int64
	Login               string
	Email               string
	DisplayName         string
	AvatarUrl           string
	IsBootstrapAdmin    int64
	CreatedAt           string
	UpdatedAt           string
	GithubUserID        *int64
	GithubInstanceID    *int64
	GitlabUserID        *int64
	GitlabInstanceID    *int64
	BitbucketUserID     *int64
	BitbucketInstanceID *int64
}

type UserRepositoryAccess struct {
	UserID     int64
	RepoID     int64
	Permission string
	CheckedAt  string
}

type UserToken struct {
	UserID                 int64
	InstanceID             int64
	AccessTokenCiphertext  string
	RefreshTokenCiphertext string
	ExpiresAt              *string
}

type WallboardToken struct {
	ID              int64
	Name            string
	TokenHash       string
	TokenPrefix     string
	CreatedByUserID *int64
	CreatedAt       string
	LastUsedAt      *string
	RevokedAt       *string
}

type WebhookEvent struct {
	ID                  int64
	InstanceID          int64
	DeliveryID          string
	EventType           string
	PayloadHash         string
	PayloadJson         string
	ReceivedAt          string
	ProcessedAt         *string
	Status              string
	Error               string
	Attempts            int64
	ProcessingStartedAt *string
}

type Workflow struct {
	ID                int64
	RepoID            int64
	Path              string
	Name              string
	ExternalIDOrPath  string
	LastSeenCommitSha string
}

type WorkflowGraph struct {
	ID        int64
	RepoID    int64
	Path      string
	CommitSha string
	NodesJson string
	CreatedAt string
}

type WorkflowRun struct {
	ID                 int64
	RepoID             int64
	WorkflowID         *int64
	ExternalID         int64
	Name               string
	Event              string
	Branch             string
	CommitSha          string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	ActorLogin         string
	HtmlUrl            string
	WorkflowPath       string
	StartedAt          *string
	CompletedAt        *string
	RunAttempt         int64
	NodeID             string
}
