// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_filters.sql

package sqlitesqlc

import (
	"context"
)

const deleteSavedFilter = `-- name: DeleteSavedFilter :exec
DELETE FROM saved_filters WHERE id = ?1 AND user_id = ?2
`

type DeleteSavedFilterParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSavedFilter(ctx context.Context, arg DeleteSavedFilterParams) error {
	_, err := q.db.ExecContext(ctx, deleteSavedFilter, arg.ID, arg.UserID)
	return err
}

const getSavedFilter = `-- name: GetSavedFilter :one
SELECT id, user_id, name, query_json, created_at, updated_at
FROM saved_filters
WHERE id = ?1 AND user_id = ?2
`

type GetSavedFilterParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSavedFilter(ctx context.Context, arg GetSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, getSavedFilter, arg.ID, arg.UserID)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSavedFilter = `-- name: InsertSavedFilter :one
INSERT INTO saved_filters (user_id, name, query_json, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, user_id, name, query_json, created_at, updated_at
`

type InsertSavedFilterParams struct {
	UserID    int64
	Name      string
	QueryJson string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) InsertSavedFilter(ctx context.Context, arg InsertSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, insertSavedFilter,
		arg.UserID,
		arg.Name,
		arg.QueryJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.QueryJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT id, user_id, name, query_json, created_at, updated_at
FROM saved_filters
WHERE user_id = ?1
ORDER BY LOWER(name) ASC, id ASC
`

func (q *Queries) ListSavedFilters(ctx context.Context, userID int64) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFilters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedFilter{}
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.QueryJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavedFilter = `-- name: UpdateSavedFilter :exec
UPDATE saved_filters SET name = ?1, query_json = ?2, updated_at = ?3
WHERE id = ?4 AND user_id = ?5
`

type UpdateSavedFilterParams struct {
	Name      string
	QueryJson string
	UpdatedAt string
	ID        int64
	UserID    int64
}

func (q *Queries) UpdateSavedFilter(ctx context.Context, arg UpdateSavedFilterParams) error {
	_, err := q.db.ExecContext(ctx, updateSavedFilter,
		arg.Name,
		arg.QueryJson,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
