apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitseer.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: gitseer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8090
