{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea-lens.fullname" . }}
  labels:
    app.kubernetes.io/name: gitea-lens
type: Opaque
stringData:
  {{- if .Values.secret.giteaToken }}
  LENS_GITEA_TOKEN: {{ .Values.secret.giteaToken | quote }}
  {{- end }}
  {{- if .Values.secret.bootstrapPassword }}
  LENS_AUTH_BOOTSTRAP_PASSWORD: {{ .Values.secret.bootstrapPassword | quote }}
  {{- end }}
  {{- if .Values.secret.oauthClientId }}
  LENS_AUTH_OAUTH_CLIENT_ID: {{ .Values.secret.oauthClientId | quote }}
  {{- end }}
  {{- if .Values.secret.oauthClientSecret }}
  LENS_AUTH_OAUTH_CLIENT_SECRET: {{ .Values.secret.oauthClientSecret | quote }}
  {{- end }}
  {{- if .Values.secret.webhookSecret }}
  LENS_WEBHOOK_SECRET: {{ .Values.secret.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.secret.encryptionKey }}
  LENS_ENCRYPTION_KEY: {{ .Values.secret.encryptionKey | quote }}
  {{- end }}
  {{- if .Values.secret.metricsToken }}
  LENS_METRICS_TOKEN: {{ .Values.secret.metricsToken | quote }}
  {{- end }}
{{- end }}
