// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package postgressqlc

import (
	"context"
)

const deleteInstanceByID = `-- name: DeleteInstanceByID :exec
DELETE FROM instances WHERE id = $1
`

func (q *Queries) DeleteInstanceByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInstanceByID, id)
	return err
}

const getInstanceByForgeAndURL = `-- name: GetInstanceByForgeAndURL :one
SELECT
  id, name, forge_type, base_url, version, capabilities_json,
  sync_token_ciphertext, webhook_secret_ciphertext,
  oauth_client_id, oauth_client_secret_ciphertext, external_url,
  allow_private_network, allow_unsigned_webhooks,
  webhook_verified_at, webhook_ensure_at, webhook_ensure_error, webhook_verify_token,
  created_at, updated_at
FROM instances
WHERE forge_type = $1 AND base_url = $2
`

type GetInstanceByForgeAndURLParams struct {
	ForgeType string
	BaseUrl   string
}

type GetInstanceByForgeAndURLRow struct {
	ID                          int64
	Name                        string
	ForgeType                   string
	BaseUrl                     string
	Version                     string
	CapabilitiesJson            string
	SyncTokenCiphertext         string
	WebhookSecretCiphertext     string
	OauthClientID               string
	OauthClientSecretCiphertext string
	ExternalUrl                 string
	AllowPrivateNetwork         int64
	AllowUnsignedWebhooks       int64
	WebhookVerifiedAt           *string
	WebhookEnsureAt             *string
	WebhookEnsureError          *string
	WebhookVerifyToken          *string
	CreatedAt                   string
	UpdatedAt                   string
}

func (q *Queries) GetInstanceByForgeAndURL(ctx context.Context, arg GetInstanceByForgeAndURLParams) (GetInstanceByForgeAndURLRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceByForgeAndURL, arg.ForgeType, arg.BaseUrl)
	var i GetInstanceByForgeAndURLRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ForgeType,
		&i.BaseUrl,
		&i.Version,
		&i.CapabilitiesJson,
		&i.SyncTokenCiphertext,
		&i.WebhookSecretCiphertext,
		&i.OauthClientID,
		&i.OauthClientSecretCiphertext,
		&i.ExternalUrl,
		&i.AllowPrivateNetwork,
		&i.AllowUnsignedWebhooks,
		&i.WebhookVerifiedAt,
		&i.WebhookEnsureAt,
		&i.WebhookEnsureError,
		&i.WebhookVerifyToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByID = `-- name: GetInstanceByID :one
SELECT
  id, name, forge_type, base_url, version, capabilities_json,
  sync_token_ciphertext, webhook_secret_ciphertext,
  oauth_client_id, oauth_client_secret_ciphertext, external_url,
  allow_private_network, allow_unsigned_webhooks,
  webhook_verified_at, webhook_ensure_at, webhook_ensure_error, webhook_verify_token,
  created_at, updated_at
FROM instances
WHERE id = $1
`

type GetInstanceByIDRow struct {
	ID                          int64
	Name                        string
	ForgeType                   string
	BaseUrl                     string
	Version                     string
	CapabilitiesJson            string
	SyncTokenCiphertext         string
	WebhookSecretCiphertext     string
	OauthClientID               string
	OauthClientSecretCiphertext string
	ExternalUrl                 string
	AllowPrivateNetwork         int64
	AllowUnsignedWebhooks       int64
	WebhookVerifiedAt           *string
	WebhookEnsureAt             *string
	WebhookEnsureError          *string
	WebhookVerifyToken          *string
	CreatedAt                   string
	UpdatedAt                   string
}

func (q *Queries) GetInstanceByID(ctx context.Context, id int64) (GetInstanceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceByID, id)
	var i GetInstanceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ForgeType,
		&i.BaseUrl,
		&i.Version,
		&i.CapabilitiesJson,
		&i.SyncTokenCiphertext,
		&i.WebhookSecretCiphertext,
		&i.OauthClientID,
		&i.OauthClientSecretCiphertext,
		&i.ExternalUrl,
		&i.AllowPrivateNetwork,
		&i.AllowUnsignedWebhooks,
		&i.WebhookVerifiedAt,
		&i.WebhookEnsureAt,
		&i.WebhookEnsureError,
		&i.WebhookVerifyToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceByURL = `-- name: GetInstanceByURL :one
SELECT
  id, name, forge_type, base_url, version, capabilities_json,
  sync_token_ciphertext, webhook_secret_ciphertext,
  oauth_client_id, oauth_client_secret_ciphertext, external_url,
  allow_private_network, allow_unsigned_webhooks,
  webhook_verified_at, webhook_ensure_at, webhook_ensure_error, webhook_verify_token,
  created_at, updated_at
FROM instances
WHERE base_url = $1
`

type GetInstanceByURLRow struct {
	ID                          int64
	Name                        string
	ForgeType                   string
	BaseUrl                     string
	Version                     string
	CapabilitiesJson            string
	SyncTokenCiphertext         string
	WebhookSecretCiphertext     string
	OauthClientID               string
	OauthClientSecretCiphertext string
	ExternalUrl                 string
	AllowPrivateNetwork         int64
	AllowUnsignedWebhooks       int64
	WebhookVerifiedAt           *string
	WebhookEnsureAt             *string
	WebhookEnsureError          *string
	WebhookVerifyToken          *string
	CreatedAt                   string
	UpdatedAt                   string
}

func (q *Queries) GetInstanceByURL(ctx context.Context, baseUrl string) (GetInstanceByURLRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceByURL, baseUrl)
	var i GetInstanceByURLRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ForgeType,
		&i.BaseUrl,
		&i.Version,
		&i.CapabilitiesJson,
		&i.SyncTokenCiphertext,
		&i.WebhookSecretCiphertext,
		&i.OauthClientID,
		&i.OauthClientSecretCiphertext,
		&i.ExternalUrl,
		&i.AllowPrivateNetwork,
		&i.AllowUnsignedWebhooks,
		&i.WebhookVerifiedAt,
		&i.WebhookEnsureAt,
		&i.WebhookEnsureError,
		&i.WebhookVerifyToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrimaryInstance = `-- name: GetPrimaryInstance :one
SELECT
  id, name, forge_type, base_url, version, capabilities_json,
  sync_token_ciphertext, webhook_secret_ciphertext,
  oauth_client_id, oauth_client_secret_ciphertext, external_url,
  allow_private_network, allow_unsigned_webhooks,
  webhook_verified_at, webhook_ensure_at, webhook_ensure_error, webhook_verify_token,
  created_at, updated_at
FROM instances
ORDER BY id ASC
LIMIT 1
`

type GetPrimaryInstanceRow struct {
	ID                          int64
	Name                        string
	ForgeType                   string
	BaseUrl                     string
	Version                     string
	CapabilitiesJson            string
	SyncTokenCiphertext         string
	WebhookSecretCiphertext     string
	OauthClientID               string
	OauthClientSecretCiphertext string
	ExternalUrl                 string
	AllowPrivateNetwork         int64
	AllowUnsignedWebhooks       int64
	WebhookVerifiedAt           *string
	WebhookEnsureAt             *string
	WebhookEnsureError          *string
	WebhookVerifyToken          *string
	CreatedAt                   string
	UpdatedAt                   string
}

func (q *Queries) GetPrimaryInstance(ctx context.Context) (GetPrimaryInstanceRow, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryInstance)
	var i GetPrimaryInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ForgeType,
		&i.BaseUrl,
		&i.Version,
		&i.CapabilitiesJson,
		&i.SyncTokenCiphertext,
		&i.WebhookSecretCiphertext,
		&i.OauthClientID,
		&i.OauthClientSecretCiphertext,
		&i.ExternalUrl,
		&i.AllowPrivateNetwork,
		&i.AllowUnsignedWebhooks,
		&i.WebhookVerifiedAt,
		&i.WebhookEnsureAt,
		&i.WebhookEnsureError,
		&i.WebhookVerifyToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstances = `-- name: ListInstances :many
SELECT
  id, name, forge_type, base_url, version, capabilities_json,
  sync_token_ciphertext, webhook_secret_ciphertext,
  oauth_client_id, oauth_client_secret_ciphertext, external_url,
  allow_private_network, allow_unsigned_webhooks,
  webhook_verified_at, webhook_ensure_at, webhook_ensure_error, webhook_verify_token,
  created_at, updated_at
FROM instances
ORDER BY id ASC
`

type ListInstancesRow struct {
	ID                          int64
	Name                        string
	ForgeType                   string
	BaseUrl                     string
	Version                     string
	CapabilitiesJson            string
	SyncTokenCiphertext         string
	WebhookSecretCiphertext     string
	OauthClientID               string
	OauthClientSecretCiphertext string
	ExternalUrl                 string
	AllowPrivateNetwork         int64
	AllowUnsignedWebhooks       int64
	WebhookVerifiedAt           *string
	WebhookEnsureAt             *string
	WebhookEnsureError          *string
	WebhookVerifyToken          *string
	CreatedAt                   string
	UpdatedAt                   string
}

func (q *Queries) ListInstances(ctx context.Context) ([]ListInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstancesRow{}
	for rows.Next() {
		var i ListInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ForgeType,
			&i.BaseUrl,
			&i.Version,
			&i.CapabilitiesJson,
			&i.SyncTokenCiphertext,
			&i.WebhookSecretCiphertext,
			&i.OauthClientID,
			&i.OauthClientSecretCiphertext,
			&i.ExternalUrl,
			&i.AllowPrivateNetwork,
			&i.AllowUnsignedWebhooks,
			&i.WebhookVerifiedAt,
			&i.WebhookEnsureAt,
			&i.WebhookEnsureError,
			&i.WebhookVerifyToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
