// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package postgressqlc

import (
	"context"
	"strings"
)

const getJobByExternalID = `-- name: GetJobByExternalID :one
SELECT id, run_id, repo_id, external_id, node_id, name, status, conclusion, upstream_status, upstream_conclusion,
       runner_id, runner_name, html_url, started_at, completed_at, steps_json, labels_json, message
FROM jobs
WHERE repo_id = $1 AND external_id = $2
`

type GetJobByExternalIDParams struct {
	RepoID     int64
	ExternalID int64
}

type GetJobByExternalIDRow struct {
	ID                 int64
	RunID              int64
	RepoID             int64
	ExternalID         int64
	NodeID             string
	Name               string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	RunnerID           *int64
	RunnerName         string
	HtmlUrl            string
	StartedAt          *string
	CompletedAt        *string
	StepsJson          *string
	LabelsJson         *string
	Message            string
}

func (q *Queries) GetJobByExternalID(ctx context.Context, arg GetJobByExternalIDParams) (GetJobByExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getJobByExternalID, arg.RepoID, arg.ExternalID)
	var i GetJobByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.ExternalID,
		&i.NodeID,
		&i.Name,
		&i.Status,
		&i.Conclusion,
		&i.UpstreamStatus,
		&i.UpstreamConclusion,
		&i.RunnerID,
		&i.RunnerName,
		&i.HtmlUrl,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StepsJson,
		&i.LabelsJson,
		&i.Message,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, run_id, repo_id, external_id, node_id, name, status, conclusion, upstream_status, upstream_conclusion,
       runner_id, runner_name, html_url, started_at, completed_at, steps_json, labels_json, message
FROM jobs
WHERE id = $1
`

type GetJobByIDRow struct {
	ID                 int64
	RunID              int64
	RepoID             int64
	ExternalID         int64
	NodeID             string
	Name               string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	RunnerID           *int64
	RunnerName         string
	HtmlUrl            string
	StartedAt          *string
	CompletedAt        *string
	StepsJson          *string
	LabelsJson         *string
	Message            string
}

func (q *Queries) GetJobByID(ctx context.Context, id int64) (GetJobByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i GetJobByIDRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.ExternalID,
		&i.NodeID,
		&i.Name,
		&i.Status,
		&i.Conclusion,
		&i.UpstreamStatus,
		&i.UpstreamConclusion,
		&i.RunnerID,
		&i.RunnerName,
		&i.HtmlUrl,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StepsJson,
		&i.LabelsJson,
		&i.Message,
	)
	return i, err
}

const listJobsByRunID = `-- name: ListJobsByRunID :many
SELECT id, run_id, repo_id, external_id, node_id, name, status, conclusion, upstream_status, upstream_conclusion,
       runner_id, runner_name, html_url, started_at, completed_at, steps_json, labels_json, message
FROM jobs
WHERE run_id = $1
ORDER BY id
`

type ListJobsByRunIDRow struct {
	ID                 int64
	RunID              int64
	RepoID             int64
	ExternalID         int64
	NodeID             string
	Name               string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	RunnerID           *int64
	RunnerName         string
	HtmlUrl            string
	StartedAt          *string
	CompletedAt        *string
	StepsJson          *string
	LabelsJson         *string
	Message            string
}

func (q *Queries) ListJobsByRunID(ctx context.Context, runID int64) ([]ListJobsByRunIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByRunIDRow{}
	for rows.Next() {
		var i ListJobsByRunIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.ExternalID,
			&i.NodeID,
			&i.Name,
			&i.Status,
			&i.Conclusion,
			&i.UpstreamStatus,
			&i.UpstreamConclusion,
			&i.RunnerID,
			&i.RunnerName,
			&i.HtmlUrl,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StepsJson,
			&i.LabelsJson,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRunIDs = `-- name: ListJobsByRunIDs :many
SELECT id, run_id, repo_id, external_id, node_id, name, status, conclusion, upstream_status, upstream_conclusion,
       runner_id, runner_name, html_url, started_at, completed_at, steps_json, labels_json, message
FROM jobs
WHERE run_id IN ($1)
ORDER BY id
`

type ListJobsByRunIDsRow struct {
	ID                 int64
	RunID              int64
	RepoID             int64
	ExternalID         int64
	NodeID             string
	Name               string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	RunnerID           *int64
	RunnerName         string
	HtmlUrl            string
	StartedAt          *string
	CompletedAt        *string
	StepsJson          *string
	LabelsJson         *string
	Message            string
}

func (q *Queries) ListJobsByRunIDs(ctx context.Context, runIds []int64) ([]ListJobsByRunIDsRow, error) {
	query := listJobsByRunIDs
	var queryParams []interface{}
	if len(runIds) > 0 {
		for _, v := range runIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:run_ids*/?", strings.Repeat(",?", len(runIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:run_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsByRunIDsRow{}
	for rows.Next() {
		var i ListJobsByRunIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.ExternalID,
			&i.NodeID,
			&i.Name,
			&i.Status,
			&i.Conclusion,
			&i.UpstreamStatus,
			&i.UpstreamConclusion,
			&i.RunnerID,
			&i.RunnerName,
			&i.HtmlUrl,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StepsJson,
			&i.LabelsJson,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
