// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: misc.sql

package postgressqlc

import (
	"context"
)

const getPostgresDatabaseSize = `-- name: GetPostgresDatabaseSize :one
SELECT pg_database_size(current_database()) AS bytes
`

func (q *Queries) GetPostgresDatabaseSize(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostgresDatabaseSize)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}
