// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: repositories.sql

package postgressqlc

import (
	"context"
)

const deleteAccessForRepo = `-- name: DeleteAccessForRepo :exec
DELETE FROM user_repository_access WHERE repo_id = $1
`

func (q *Queries) DeleteAccessForRepo(ctx context.Context, repoID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccessForRepo, repoID)
	return err
}

const getRepositoryByExternalID = `-- name: GetRepositoryByExternalID :one
SELECT id, instance_id, org_id, external_id, node_id, owner, name, full_name, default_branch,
       private, archived, empty, fork, html_url, last_synced_at, deleted_at, created_at, updated_at
FROM repositories
WHERE instance_id = $1 AND external_id = $2
`

type GetRepositoryByExternalIDParams struct {
	InstanceID int64
	ExternalID int64
}

type GetRepositoryByExternalIDRow struct {
	ID            int64
	InstanceID    int64
	OrgID         *int64
	ExternalID    int64
	NodeID        string
	Owner         string
	Name          string
	FullName      string
	DefaultBranch string
	Private       int64
	Archived      int64
	Empty         int64
	Fork          int64
	HtmlUrl       string
	LastSyncedAt  *string
	DeletedAt     *string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) GetRepositoryByExternalID(ctx context.Context, arg GetRepositoryByExternalIDParams) (GetRepositoryByExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByExternalID, arg.InstanceID, arg.ExternalID)
	var i GetRepositoryByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.OrgID,
		&i.ExternalID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Private,
		&i.Archived,
		&i.Empty,
		&i.Fork,
		&i.HtmlUrl,
		&i.LastSyncedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, instance_id, org_id, external_id, node_id, owner, name, full_name, default_branch,
       private, archived, empty, fork, html_url, last_synced_at, deleted_at, created_at, updated_at
FROM repositories
WHERE id = $1
`

type GetRepositoryByIDRow struct {
	ID            int64
	InstanceID    int64
	OrgID         *int64
	ExternalID    int64
	NodeID        string
	Owner         string
	Name          string
	FullName      string
	DefaultBranch string
	Private       int64
	Archived      int64
	Empty         int64
	Fork          int64
	HtmlUrl       string
	LastSyncedAt  *string
	DeletedAt     *string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) GetRepositoryByID(ctx context.Context, id int64) (GetRepositoryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByID, id)
	var i GetRepositoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.OrgID,
		&i.ExternalID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Private,
		&i.Archived,
		&i.Empty,
		&i.Fork,
		&i.HtmlUrl,
		&i.LastSyncedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByOwnerNameInInstance = `-- name: GetRepositoryByOwnerNameInInstance :one
SELECT id, instance_id, org_id, external_id, node_id, owner, name, full_name, default_branch,
       private, archived, empty, fork, html_url, last_synced_at, deleted_at, created_at, updated_at
FROM repositories
WHERE instance_id = $1
  AND owner = $2
  AND name = $3
  AND deleted_at IS NULL
`

type GetRepositoryByOwnerNameInInstanceParams struct {
	InstanceID int64
	Owner      string
	Name       string
}

type GetRepositoryByOwnerNameInInstanceRow struct {
	ID            int64
	InstanceID    int64
	OrgID         *int64
	ExternalID    int64
	NodeID        string
	Owner         string
	Name          string
	FullName      string
	DefaultBranch string
	Private       int64
	Archived      int64
	Empty         int64
	Fork          int64
	HtmlUrl       string
	LastSyncedAt  *string
	DeletedAt     *string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) GetRepositoryByOwnerNameInInstance(ctx context.Context, arg GetRepositoryByOwnerNameInInstanceParams) (GetRepositoryByOwnerNameInInstanceRow, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByOwnerNameInInstance, arg.InstanceID, arg.Owner, arg.Name)
	var i GetRepositoryByOwnerNameInInstanceRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.OrgID,
		&i.ExternalID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Private,
		&i.Archived,
		&i.Empty,
		&i.Fork,
		&i.HtmlUrl,
		&i.LastSyncedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoriesByOwnerName = `-- name: ListRepositoriesByOwnerName :many
SELECT id, instance_id, org_id, external_id, node_id, owner, name, full_name, default_branch,
       private, archived, empty, fork, html_url, last_synced_at, deleted_at, created_at, updated_at
FROM repositories
WHERE owner = $1 AND name = $2 AND deleted_at IS NULL
ORDER BY id ASC
`

type ListRepositoriesByOwnerNameParams struct {
	Owner string
	Name  string
}

type ListRepositoriesByOwnerNameRow struct {
	ID            int64
	InstanceID    int64
	OrgID         *int64
	ExternalID    int64
	NodeID        string
	Owner         string
	Name          string
	FullName      string
	DefaultBranch string
	Private       int64
	Archived      int64
	Empty         int64
	Fork          int64
	HtmlUrl       string
	LastSyncedAt  *string
	DeletedAt     *string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) ListRepositoriesByOwnerName(ctx context.Context, arg ListRepositoriesByOwnerNameParams) ([]ListRepositoriesByOwnerNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoriesByOwnerName, arg.Owner, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepositoriesByOwnerNameRow{}
	for rows.Next() {
		var i ListRepositoriesByOwnerNameRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.OrgID,
			&i.ExternalID,
			&i.NodeID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.DefaultBranch,
			&i.Private,
			&i.Archived,
			&i.Empty,
			&i.Fork,
			&i.HtmlUrl,
			&i.LastSyncedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRepository = `-- name: SoftDeleteRepository :exec
UPDATE repositories
SET deleted_at = $1, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type SoftDeleteRepositoryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) SoftDeleteRepository(ctx context.Context, arg SoftDeleteRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteRepository, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}
