// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package postgressqlc

import (
	"context"
)

const countWorkflowRuns = `-- name: CountWorkflowRuns :one
SELECT COUNT(*) FROM workflow_runs
`

func (q *Queries) CountWorkflowRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkflowRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkflowRunByExternalID = `-- name: GetWorkflowRunByExternalID :one
SELECT wr.id, wr.repo_id, wr.workflow_id, wr.external_id, wr.node_id, wr.name, wr.event, wr.branch, wr.commit_sha,
       wr.status, wr.conclusion, wr.upstream_status, wr.upstream_conclusion, wr.actor_login, wr.html_url,
       wr.workflow_path, wr.started_at, wr.completed_at, wr.run_attempt, r.owner, r.name, r.full_name
FROM workflow_runs wr
JOIN repositories r ON r.id = wr.repo_id
WHERE wr.repo_id = $1 AND wr.external_id = $2
`

type GetWorkflowRunByExternalIDParams struct {
	RepoID     int64
	ExternalID int64
}

type GetWorkflowRunByExternalIDRow struct {
	ID                 int64
	RepoID             int64
	WorkflowID         *int64
	ExternalID         int64
	NodeID             string
	Name               string
	Event              string
	Branch             string
	CommitSha          string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	ActorLogin         string
	HtmlUrl            string
	WorkflowPath       string
	StartedAt          *string
	CompletedAt        *string
	RunAttempt         int64
	Owner              string
	Name_2             string
	FullName           string
}

func (q *Queries) GetWorkflowRunByExternalID(ctx context.Context, arg GetWorkflowRunByExternalIDParams) (GetWorkflowRunByExternalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRunByExternalID, arg.RepoID, arg.ExternalID)
	var i GetWorkflowRunByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowID,
		&i.ExternalID,
		&i.NodeID,
		&i.Name,
		&i.Event,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.Conclusion,
		&i.UpstreamStatus,
		&i.UpstreamConclusion,
		&i.ActorLogin,
		&i.HtmlUrl,
		&i.WorkflowPath,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunAttempt,
		&i.Owner,
		&i.Name_2,
		&i.FullName,
	)
	return i, err
}

const getWorkflowRunByID = `-- name: GetWorkflowRunByID :one
SELECT wr.id, wr.repo_id, wr.workflow_id, wr.external_id, wr.node_id, wr.name, wr.event, wr.branch, wr.commit_sha,
       wr.status, wr.conclusion, wr.upstream_status, wr.upstream_conclusion, wr.actor_login, wr.html_url,
       wr.workflow_path, wr.started_at, wr.completed_at, wr.run_attempt, r.owner, r.name, r.full_name,
       COALESCE(NULLIF(TRIM(i.forge_type), ''), 'gitea'), r.instance_id, COALESCE(i.name, '')
FROM workflow_runs wr
JOIN repositories r ON r.id = wr.repo_id
LEFT JOIN instances i ON i.id = r.instance_id
WHERE wr.id = $1
`

type GetWorkflowRunByIDRow struct {
	ID                 int64
	RepoID             int64
	WorkflowID         *int64
	ExternalID         int64
	NodeID             string
	Name               string
	Event              string
	Branch             string
	CommitSha          string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	ActorLogin         string
	HtmlUrl            string
	WorkflowPath       string
	StartedAt          *string
	CompletedAt        *string
	RunAttempt         int64
	Owner              string
	Name_2             string
	FullName           string
	Coalesce           interface{}
	InstanceID         int64
	Name_3             string
}

func (q *Queries) GetWorkflowRunByID(ctx context.Context, id int64) (GetWorkflowRunByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRunByID, id)
	var i GetWorkflowRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.WorkflowID,
		&i.ExternalID,
		&i.NodeID,
		&i.Name,
		&i.Event,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.Conclusion,
		&i.UpstreamStatus,
		&i.UpstreamConclusion,
		&i.ActorLogin,
		&i.HtmlUrl,
		&i.WorkflowPath,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunAttempt,
		&i.Owner,
		&i.Name_2,
		&i.FullName,
		&i.Coalesce,
		&i.InstanceID,
		&i.Name_3,
	)
	return i, err
}

const listInFlightWorkflowRunsByRepo = `-- name: ListInFlightWorkflowRunsByRepo :many
SELECT wr.id, wr.repo_id, wr.workflow_id, wr.external_id, wr.node_id, wr.name, wr.event, wr.branch, wr.commit_sha,
       wr.status, wr.conclusion, wr.upstream_status, wr.upstream_conclusion, wr.actor_login, wr.html_url,
       wr.workflow_path, wr.started_at, wr.completed_at, wr.run_attempt, r.owner, r.name, r.full_name
FROM workflow_runs wr
JOIN repositories r ON r.id = wr.repo_id
WHERE wr.repo_id = $1 AND wr.status IN ('queued', 'waiting', 'running')
ORDER BY wr.id DESC
`

type ListInFlightWorkflowRunsByRepoRow struct {
	ID                 int64
	RepoID             int64
	WorkflowID         *int64
	ExternalID         int64
	NodeID             string
	Name               string
	Event              string
	Branch             string
	CommitSha          string
	Status             string
	Conclusion         string
	UpstreamStatus     string
	UpstreamConclusion string
	ActorLogin         string
	HtmlUrl            string
	WorkflowPath       string
	StartedAt          *string
	CompletedAt        *string
	RunAttempt         int64
	Owner              string
	Name_2             string
	FullName           string
}

func (q *Queries) ListInFlightWorkflowRunsByRepo(ctx context.Context, repoID int64) ([]ListInFlightWorkflowRunsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listInFlightWorkflowRunsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInFlightWorkflowRunsByRepoRow{}
	for rows.Next() {
		var i ListInFlightWorkflowRunsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.WorkflowID,
			&i.ExternalID,
			&i.NodeID,
			&i.Name,
			&i.Event,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.Conclusion,
			&i.UpstreamStatus,
			&i.UpstreamConclusion,
			&i.ActorLogin,
			&i.HtmlUrl,
			&i.WorkflowPath,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunAttempt,
			&i.Owner,
			&i.Name_2,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
