// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package postgressqlc

import (
	"context"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT
  instance_name, sync_history_days, attention_long_running_after,
  retention_runs_days, retention_webhooks_days, retention_attention_days,
  server_external_url,
  gitea_url, gitea_token_cipher, gitea_webhook_secret_cipher,
  gitea_allow_private_network, gitea_allow_unsigned_webhooks,
  oauth_client_id, oauth_client_secret_cipher, setup_completed, updated_at
FROM app_settings
WHERE id = 1
`

type GetAppSettingsRow struct {
	InstanceName               string
	SyncHistoryDays            int64
	AttentionLongRunningAfter  string
	RetentionRunsDays          int64
	RetentionWebhooksDays      int64
	RetentionAttentionDays     int64
	ServerExternalUrl          string
	GiteaUrl                   string
	GiteaTokenCipher           string
	GiteaWebhookSecretCipher   string
	GiteaAllowPrivateNetwork   *int64
	GiteaAllowUnsignedWebhooks *int64
	OauthClientID              string
	OauthClientSecretCipher    string
	SetupCompleted             int64
	UpdatedAt                  string
}

func (q *Queries) GetAppSettings(ctx context.Context) (GetAppSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i GetAppSettingsRow
	err := row.Scan(
		&i.InstanceName,
		&i.SyncHistoryDays,
		&i.AttentionLongRunningAfter,
		&i.RetentionRunsDays,
		&i.RetentionWebhooksDays,
		&i.RetentionAttentionDays,
		&i.ServerExternalUrl,
		&i.GiteaUrl,
		&i.GiteaTokenCipher,
		&i.GiteaWebhookSecretCipher,
		&i.GiteaAllowPrivateNetwork,
		&i.GiteaAllowUnsignedWebhooks,
		&i.OauthClientID,
		&i.OauthClientSecretCipher,
		&i.SetupCompleted,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowGraph = `-- name: GetWorkflowGraph :one
SELECT nodes_json FROM workflow_graphs
WHERE repo_id = $1 AND path = $2 AND commit_sha = $3
`

type GetWorkflowGraphParams struct {
	RepoID    int64
	Path      string
	CommitSha string
}

func (q *Queries) GetWorkflowGraph(ctx context.Context, arg GetWorkflowGraphParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowGraph, arg.RepoID, arg.Path, arg.CommitSha)
	var nodes_json string
	err := row.Scan(&nodes_json)
	return nodes_json, err
}

const upsertWorkflowGraph = `-- name: UpsertWorkflowGraph :exec
INSERT INTO workflow_graphs (repo_id, path, commit_sha, nodes_json)
VALUES ($1, $2, $3, $4)
ON CONFLICT(repo_id, path, commit_sha) DO UPDATE SET nodes_json = excluded.nodes_json
`

type UpsertWorkflowGraphParams struct {
	RepoID    int64
	Path      string
	CommitSha string
	NodesJson string
}

func (q *Queries) UpsertWorkflowGraph(ctx context.Context, arg UpsertWorkflowGraphParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowGraph,
		arg.RepoID,
		arg.Path,
		arg.CommitSha,
		arg.NodesJson,
	)
	return err
}
