// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallboard.sql

package postgressqlc

import (
	"context"
)

const getWallboardTokenByID = `-- name: GetWallboardTokenByID :one
SELECT id, name, token_prefix, created_by_user_id, created_at, last_used_at, revoked_at
FROM wallboard_tokens
WHERE id = $1
`

type GetWallboardTokenByIDRow struct {
	ID              int64
	Name            string
	TokenPrefix     string
	CreatedByUserID *int64
	CreatedAt       string
	LastUsedAt      *string
	RevokedAt       *string
}

func (q *Queries) GetWallboardTokenByID(ctx context.Context, id int64) (GetWallboardTokenByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWallboardTokenByID, id)
	var i GetWallboardTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listWallboardTokensActive = `-- name: ListWallboardTokensActive :many
SELECT id, name, token_prefix, created_by_user_id, created_at, last_used_at, revoked_at
FROM wallboard_tokens
WHERE revoked_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListWallboardTokensActiveRow struct {
	ID              int64
	Name            string
	TokenPrefix     string
	CreatedByUserID *int64
	CreatedAt       string
	LastUsedAt      *string
	RevokedAt       *string
}

func (q *Queries) ListWallboardTokensActive(ctx context.Context) ([]ListWallboardTokensActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listWallboardTokensActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWallboardTokensActiveRow{}
	for rows.Next() {
		var i ListWallboardTokensActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWallboardTokensAll = `-- name: ListWallboardTokensAll :many
SELECT id, name, token_prefix, created_by_user_id, created_at, last_used_at, revoked_at
FROM wallboard_tokens
ORDER BY created_at DESC, id DESC
`

type ListWallboardTokensAllRow struct {
	ID              int64
	Name            string
	TokenPrefix     string
	CreatedByUserID *int64
	CreatedAt       string
	LastUsedAt      *string
	RevokedAt       *string
}

func (q *Queries) ListWallboardTokensAll(ctx context.Context) ([]ListWallboardTokensAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listWallboardTokensAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWallboardTokensAllRow{}
	for rows.Next() {
		var i ListWallboardTokensAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWallboardToken = `-- name: RevokeWallboardToken :exec
UPDATE wallboard_tokens SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeWallboardTokenParams struct {
	RevokedAt *string
	ID        int64
}

func (q *Queries) RevokeWallboardToken(ctx context.Context, arg RevokeWallboardTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeWallboardToken, arg.RevokedAt, arg.ID)
	return err
}
